# Generated by Django 4.2.1 on 2023-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('sentiment', models.CharField(max_length=50)),
                ('branch_id', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_login',
            name='branches_alloted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user_login',
            name='role',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user_login',
            name='user_id',
            field=models.TextField(blank=True),
        ),
    ]
