# Generated by Django 4.2.1 on 2023-08-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0004_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviews',
        ),
    ]
