# Generated by Django 4.2.1 on 2023-08-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0005_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('rating', models.TextField()),
                ('date', models.DateTimeField()),
                ('sentiment', models.CharField(max_length=50)),
                ('branch_id', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
            ],
        ),
    ]
