# Generated by Django 4.2.1 on 2023-08-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0007_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='client_id',
            field=models.TextField(blank=True),
        ),
    ]
