# Generated by Django 4.2.1 on 2023-08-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0009_competitor_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='competitor_reviews',
        ),
    ]
